export const btn_dn = [
  "https://gransaga.com/assets/images/desktop/main/btn_dn_google.png?v=00000000",
  "https://gransaga.com/assets/images/desktop/main/btn_dn_apple.png?v=00000000",
  "https://gransaga.com/assets/images/desktop/main/btn_dn_onestore.png?v=00000000",
  "https://gransaga.com/assets/images/desktop/main/btn_dn_galaxy.png?v=00000000",
  "https://gransaga.com/assets/images/desktop/main/btn_dn_pc.png?v=00000000",
  "https://gransaga.com/assets/images/desktop/main/btn_dn_mac.png?v=00000000",
];

export const image = [
  "https://gransaga.com/download/poster/download_066.jpg",
  "https://gransaga.com/download/poster/download_056.jpg",
  "https://gransaga.com/download/poster/download_050.jpg",
  "https://gransaga.com/download/poster/download_047.jpg",
  "https://gransaga.com/download/poster/download_045.jpg",
  "https://gransaga.com/download/poster/download_043.jpg",
  // "https://gransaga.com/download/poster/download_034.jpg",
  // "https://gransaga.com/download/poster/download_031_2.jpg",
  // "https://gransaga.com/download/poster/download_031_1.jpg",
  // "https://gransaga.com/download/poster/download_025.jpg",
  // "https://gransaga.com/download/poster/download_024.jpg",
  // "https://gransaga.com/download/poster/download_023.jpg",
  // "https://gransaga.com/download/poster/download_019.jpg",
  // "https://gransaga.com/download/poster/download_015.jpg",
  // "https://gransaga.com/download/poster/download_010.jpg",
  // "https://gransaga.com/download/poster/download_009.jpg",
  // "https://gransaga.com/download/poster/download_008.jpg",
  // "https://gransaga.com/download/poster/download_007.jpg",
  // "https://gransaga.com/download/poster/download_006.jpg",
  // "https://gransaga.com/download/poster/download_005.jpg",
  // "https://gransaga.com/download/poster/download_004.jpg",
  // "https://gransaga.com/download/poster/download_003.jpg",
  // "https://gransaga.com/download/poster/download_002.jpg",
  // "https://gransaga.com/download/poster/download_001.jpg",
];
